version: "3.5"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: book-mcsv
      POSTGRES_PASSWORD: postgres!
## É necessário incluir o IPAddress no Hostname/address do campo Connection , ao realizar a conexão com o BD no PGAdmin => docker inspect container_id '8bc5a5e5bc9e' na raiz
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  product:
    image: product
    ports:
      - "8081:8081"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/book-mcsv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres!
    depends_on:
      - postgres

  user:
    image: user
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/book-mcsv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres!
    depends_on:
      - postgres

  shopping:
    image: shopping
    ports:
      - "8082:8082"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/book-mcsv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres!
      PRODUCT_API_URL: localhost:8081
      USER_API_URL: localhost:8080
    depends_on:
      - postgres