apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
  labels:
    app: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          image: loja/shopping:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_url
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_password
            - name: PRODUCT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: shopping-configmap
                  key: product_api_url
            - name: USER_API_URL
              valueFrom:
                configMapKeyRef:
                  name: shopping-configmap
                  key: user_api_url